[build]
  base = "frontend"
  command = "make -C .. build"
  publish = "out"

[functions]
  directory = "frontend/functions"

[build.environment]
  GO_IMPORT_PATH = "github.com/eyalch/kurzr"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/kurzr/:splat"
  status = 200
