[build]
  base = "frontend"
  command = "make -C .. build"
  publish = "out"

[functions]
  directory = "frontend/functions"

[build.environment]
  GO_IMPORT_PATH = "github.com/somnambul1st/blyacc"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/somnambul1st/:splat"
  status = 200
